AddModelVirtualAttributeCheck: { }

#TODO-low restore
#AlwaysAddDbIndexCheck: { }

#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
#IsolateSeedDataCheck: { }

# becase Stripe API calls are intepreted as regular activerecord model calls
KeepFindersOnTheirOwnModelCheck: { ignored_files: 'app/models/organization.rb' }
#LawOfDemeterCheck: { }
#LongLineCheck: { max_line_length: 80 }
#MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }

#TODO-low restore
#MoveModelLogicIntoModelCheck: { use_count: 4 }

NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
#NotUseTimeAgoInWordsCheck: { }

#TODO-low make it less
OveruseRouteCustomizationsCheck: { customize_count: 6 }

ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
#RemoveTrailingWhitespaceCheck: { ignore_files: [] }
#RemoveUnusedMethodsInControllersCheck: { except_methods: ['Api::V1::ApplicationController#restrict_access', '*#index', '*#show', '*#create', 'LeaderbitsController#start', 'ApplicationController#entry_groups_includes_clause', 'EntriesController#specific_user_clause', 'UsersController#validate_role_presence_if_set', '*#visible_by_role_clause', '*#unseen_by_role_clause', 'ApplicationController#after_sign_out_path_for', 'LeaderbitsController#visibility_clause'] }
#RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
#RemoveUnusedMethodsInModelsCheck: { except_methods: ['User#only_active_leaderbits', 'User#exclude_already_received_leaderbits', '*#cache_versioning', '*#inheritance_column', 'User#rollbar_person_email_method'] }

#TODO-low restore
#ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }

#TODO-low restore. find a way to exlude just app/views/entries/_entry_group_show.html.slim:22
#ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }

#TODO-low restore
#SimplifyRenderInViewsCheck: { }

#UseBeforeFilterCheck: { customize_count: 2 }

#TODO-low restore
#UseModelAssociationCheck: { }

#UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }

#UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }

#one warning in users#show
#UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
